import { useState } from "react";
import { Button } from "../base/buttons/button";
import TermsModal from "../modals/TermsModal";
import { useModalConfig } from "@/hooks/useModalConfig";

interface DeclarationsProps {
  readonly className?: string;
}

export default function Declarations({ className = "" }: Readonly<DeclarationsProps>) {
  const [isTermsModalOpen, setIsTermsModalOpen] = useState(false);
  const [isPrivacyModalOpen, setIsPrivacyModalOpen] = useState(false);

  const updateDeclarationTermsModal = useModalConfig("updateDeclarationTerms", {
    isOpen: isTermsModalOpen,
    onClose: () => setIsTermsModalOpen(false),
  });
  const updateDeclarationPrivacyModal = useModalConfig("updateDeclarationPrivacy", {
    isOpen: isPrivacyModalOpen,
    onClose: () => setIsPrivacyModalOpen(false),
  });

  return (
    <div data-testid="declarations" className={`w-full ${className}`}>
      <p className="text-xs leading-4 font-normal text-ws-text-primary ">
        A2B provides general informational insights based on aggregated, anonymized data and
        industry benchmarks. It is intended for informational and research purposes only and is not
        a substitute for professional advice. Nothing generated by A2B constitutes or should be
        construed as legal, financial, tax, benefits, investment, or regulatory compliance advice.
        Decisions made in reliance on A2B outputs are solely your responsibility. To the fullest
        extent permitted by law, Lafayette Square and its affiliates, officers, and agents disclaim
        all liability for any loss, damage, or harm arising from your use of, or reliance on, A2B or
        its outputs. Your use of A2B is governed by our{" "}
        <Button
          color="link"
          size="sm"
          onClick={() => setIsTermsModalOpen(true)}
          className="text-xs text-ws-light-teal-850 underline p-0 m-0 h-5"
        >
          Terms of Use
        </Button>{" "}
        and{" "}
        <Button
          color="link"
          size="sm"
          onClick={() => setIsPrivacyModalOpen(true)}
          className="text-xs text-ws-light-teal-850 underline p-0 m-0 h-5"
        >
          Privacy Notice
        </Button>
      </p>
      <TermsModal
        isOpen={isTermsModalOpen}
        onClose={() => setIsTermsModalOpen(false)}
        {...updateDeclarationTermsModal}
      />
      <TermsModal
        isOpen={isPrivacyModalOpen}
        onClose={() => setIsPrivacyModalOpen(false)}
        {...updateDeclarationPrivacyModal}
      />
    </div>
  );
}
